ARG BUILD_FROM=python:3.13-alpine
FROM ${BUILD_FROM}

WORKDIR /app
COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt

COPY app/ /app/app/
COPY run.sh /run.sh
RUN chmod a+x /run.sh

CMD ["/run.sh"]
